### ISSUE TITLE
ems or rems?

### ISSUE THREAD

**Issue by ricardoom** [NYPL/design-toolkit#35]
@mgiraldo, 
Noticing in a couple places ems are being used instead of rems... is this intentional? Could you explain?

here's one place where I noticed...
https://github.com/NYPL/design-toolkit/blob/master/sass/_buttons.scss#L29

Obviously its not a major issue, just curious..

**Comment by mgiraldo** [comment]
sure. in the case you point out, one can change the font size of the button. if for whatever reason the user applies px based measurements, the rem (i think) will not be proportional to the custom font size. using em guarantees in this case that the padding will be proportional.

it is also a bad example because user can also apply custom padding in other parts so it is kind of moot.

in general, i use ems if i prefer the element to be proportional with itself (or its parent). but maybe we shouldn't do this and do everything rem?

**Comment by mgiraldo** [comment]
rems FTW
