### ISSUE TITLE
Add next/prev pagination design for buttons

### ISSUE THREAD

**Issue by EdwinGuzman** [NYPL/design-toolkit#60]
In the case of the Discovery UI, the pagination buttons are buttons and not links. Can you add the same styling for the `a` to `button`? Since it is a single-page app, no links are needed.

Also, where can I find the SVG for the left and right arrows?

**Comment by mgiraldo** [comment]
the svg for the arrows (and the microformat itself) is [in the toolkit](https://nypl.github.io/design-toolkit/sections/tables.html#pagination)

the recommendation still is to use the `a` tag instead because of the benefits of the use of `rel=prev/next`

see also:
https://webmasters.googleblog.com/2011/09/pagination-with-relnext-and-relprev.html
https://html.spec.whatwg.org/multipage/semantics.html#sequential-link-types

**Comment by EdwinGuzman** [comment]
@ricardoom those SVGs are not in the react-svg package, correct?

@mgiraldo I'll leave them as links for now but do want to get back to them later on.

**Comment by ricardoom** [comment]
no, @mgiraldo is using a different icon

**Comment by EdwinGuzman** [comment]
Think I should add them to the repo?

**Comment by mgiraldo** [comment]
see also: http://uxmovement.com/buttons/when-to-use-a-button-or-link/
